# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - '*'
    exclude:
    - master

pool:
  vmImage: 'vs2017-win2016'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: PowerShell@2
  displayName: "Install scoop"
  env:
    SCOOP: $(Agent.BuildDirectory)\SCOOP\
  inputs:
    targetType: 'inline'
    script: 'iex (new-object net.webclient).downloadstring(''https://get.scoop.sh'')'

- task: PowerShell@2
  displayName: "Add scoop shims to path"
  env:
    SCOOP: $(Agent.BuildDirectory)\SCOOP\
  inputs:
    targetType: 'inline'
    script: 'Write-Host "##vso[task.prependpath]$env:SCOOP\Shims"'
  
- script: scoop install hub
  displayName: "Install hub"
  env:
    SCOOP: $(Agent.BuildDirectory)\SCOOP\

- script: |
    git config --local user.name "Azure Pipelines"
    git config --local user.email "azuredevops@microsoft.com"
  displayName: "Set git config"

- task: PowerShell@2
  displayName: "Rewrite PR script to use ***NO_CI***"
  env:
    SCOOP: $(Agent.BuildDirectory)\SCOOP\
    SCOOP_HOME: $(Agent.BuildDirectory)\SCOOP\apps\scoop\current
  inputs:
    targetType: 'inline'
    script: |
      if(!$env:SCOOP_HOME) { $env:SCOOP_HOME = resolve-path (split-path (split-path (scoop which scoop))) }
      $autopr = "$env:SCOOP_HOME/bin/auto-pr.ps1"
      (Get-Content $autopr).replace('execute "hub commit -m \'${app}: Update to version $version\'"', 'execute "hub commit -m \'${app}: Update to version $version\' ***NO_CI***"') | Set-Content $autopr

- task: PowerShell@2
  displayName: "Run Auto-PR"
  env:
    SCOOP: $(Agent.BuildDirectory)\SCOOP\
    SCOOP_HOME: $(Agent.BuildDirectory)\SCOOP\apps\scoop\current
  inputs:
    filePath: './bin/auto-pr.ps1'
    arguments: -p
